project:
  type: website
  output-dir: docs

website:
  title: "Emma McLaughlin"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - project.qmd
    
    tools:
     # - icon: twitter
      #  href: https://x.com
     # - icon: linkedin
     #   href: https://www.linkedin.com/
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/emmamclaughlin/emmamclaughlin.github.io
          - text: Report a Bug
            href: https://github.com  

format:
  html:
    theme: journal  # flatly, litera, lumen, lux, minty, pulse, sandstone, zephyr, quartz, yeti, cosmo, sketchy
    css: styles.css
    toc: true

execute: 
  freeze: auto

