---
title: "Involvement"
---

**Club Involvement**

Lead team for Presbyterian Episcopalian campus ministry. This club promotes community, service, and learning. As a member of the lead team I plan and run events and send monthly updates to churches that donate to our organization. 


**Scholarship Program**

Plemmons Scholars Program. Since my freshman year at App State I have been a part of the Plemmons Scholarship program which is a group of about ten people from each year at App state. We get together to discuss leadership, learn new skills at weekly meetings and hear from community members. Learn more [here](https://cel.appstate.edu/programs/plemmons-leaders/)

**Travel Program**

Up With People Voices Program. During the Summer and Fall of 2023 I participated in a cultural exchange program where I traveled to four different countries in three months. During this program we put on a show promoting positive change, participated in service projects, and stayed with host families local to the community. Learn more [here](https://upwithpeople.org/voices/)

**Work Experience**

YMCA Camp counselor. For the past two summers I have worked as a summer camp counselor at the YMCA. Here I led campers in group activities, such as field trips, crafts, and learning assignments. 

App State Dining employee. As a student I work on campus at one of the campus dining location.

